fs = 24e4;
lp_cutoff = 1e5;
lpFilt = designfilt ( 'lowpassfir' , ...
    'PassbandFrequency' , lp_cutoff , ...
    'StopbandFrequency' , lp_cutoff * 1.2 , ...
    'SampleRate' , fs , ...
    'DesignMethod' , 'equiripple');
%% step 2 -- getting the (sterio) L+R signal --
fs = 24e4;
lp_cutoff2 = 1.5e4;
lpFilt2 = designfilt ( 'lowpassfir' , ...
'PassbandFrequency' , lp_cutoff2 , ...
'StopbandFrequency' , 1.7e4 , ...
'SampleRate' , fs , ...
'DesignMethod' , 'equiripple') ;
%%
centerFreq_MHz = 93.5;
sampleRate = 240e3 ;
audioFs = 48e3 ;
if exist ('radio','var') , release ( radio ) ; clear radio ; end
if exist ('specAnalyzer','var') , release ( specAnalyzer ) ; clear specAnalyzer ; end
if exist ('fmDemod','var') , release ( fmDemod ) ; clear fmDemod ; end
if exist ('player','var') , release ( player ) ; clear player ; end
player = audioDeviceWriter ('SampleRate', audioFs ) ;
%recieve sgnal
radio = comm . SDRRTLReceiver ( ...
    'CenterFrequency', centerFreq_MHz *1e6 , ...
    'SampleRate', sampleRate , ...
    'OutputDataType', 'double', ...
    'EnableTunerAGC', false , ...
    'TunerGain', 50,...
    
'SamplesPerFrame', 1024*14) ;

%analyze the spectrum
specAnalyzer = dsp.SpectrumAnalyzer ( ...
    'SampleRate', sampleRate , ...
    'SpectrumType', 'Power', ...
    'Title', 'RTL_SDL_Real_Time_Spectrum', ...
    'ShowLegend', true ) ;
%demodulation
%fmDemod = comm.FMBroadcastDemodulator ( ...
%'SampleRate', sampleRate , ...
%'FrequencyDeviation', 75e3 , ...
%'AudioSampleRate', audioFs ) ;
% playing
%player = audioDeviceWriter ('SampleRate', audioFs ) ;
while true
    iq = double ( radio () ) ;
    iq = iq / max ( abs ( iq ) ) ; % Normalize
    filteredSignal = filter ( lpFilt , iq ) ;
    % -- getting the phase, diffferentiating it & removing its DC --
    instPhase = unwrap ( angle ( filteredSignal ) ) ;
    demodulated = diff ( instPhase ) ;
    demodulated = demodulated - mean ( demodulated ) ;
    filteredSignal2 = filter ( lpFilt2 , demodulated ) ;
    %step 3 -- decimation of L+R signal --
    decimation_factor = 5;%floor ( fs / aud% io_fs ) ;
    audio = decimate(filteredSignal2 , decimation_factor ) ;
    audio = audio / max ( abs ( audio ) ) ;
    % -- playing the L+R signal
    %sound ( audio , fs/decimation_factor ) ;
    specAnalyzer ( iq ) ;
    %audio = fmDemod ( double ( iq ) ) ;
    player ( audio ) ;
end
